# Generated by Django 4.2 on 2024-04-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenAssistantDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=1000, unique=True)),
                ('answer', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
