# Generated by Django 4.2 on 2024-04-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_greenassistantdb_delete_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenassistantdb',
            old_name='prompt',
            new_name='question',
        ),
    ]
