# Generated by Django 4.2 on 2024-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_prompt_greenassistantdb_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenassistantdb',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
    ]
