# Generated by Django 4.2 on 2024-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmdata",
            name="content",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
