# Generated by Django 4.2 on 2024-05-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_llmdata_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmdata",
            name="content",
        ),
    ]
